{% set name = "dataclass-wizard" %}
{% set version = "0.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dd295cff8df6d8167a79048b77e91a3a1287a5905363f8df4de819b50d83b03a

build:
  number: 0
  noarch: python
  entry_points:
    - wiz={{ name|replace('-', '_') }}.wizard_cli.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - typing-extensions >=3.7.4.2

test:
  imports:
    - {{ name|replace('-', '_') }}
  requires:
    - pip
  commands:
    - pip check
    - wiz --help

about:
  home: https://github.com/rnag/dataclass-wizard
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Marshal dataclasses to/from JSON. Use field properties with initial values. Construct a dataclass schema with JSON input.
  description: |
    The dataclass-wizard library provides a set of simple, yet
    elegant *wizarding* tools for interacting with the Python
    `dataclasses` module in Python 3.6+.

    The primary use is as a fast serialization framework that enables
    dataclass instances to be converted to/from JSON; this works well
    in particular with a *nested dataclass* model.

    The dataclass-wizard is pure Python code that relies entirely on
    stdlib, with the only added dependency being
    `typing-extensions` <https://pypi.org/project/typing-extensions/>
    for Python 3.9 and below.
  doc_url: https://dataclass-wizard.readthedocs.io/
  dev_url: https://github.com/rnag/dataclass-wizard

extra:
  recipe-maintainers:
    - '0xbe7a'
    - 'rnag'
